### PR TITLE
[BUGFIX] Avoid race condition problem

### PR DESCRIPTION
**Pull request by alaibe**

### CODE REVIEW

**Comment by NelsonMorales** [comment]
👍

**Comment by alexdesi** [comment]
👍 maybe we'll find something better, but it does it's job!

**Comment by os6sense** [comment]
Its actually the recommended way to handle one of this class of problems that transactions create: https://github.com/mperham/sidekiq/wiki/Problems-and-Troubleshooting#activerecord however its not quite a magic bullet I think you'll find ... ;)

**Comment by os6sense** [comment]
👍

**Pull request merged**
